import type { PlantillaLayout } from './types'

const M = 14
const W = 182
const NARANJA = '#E8650A'

/** Layout IB de referencia para presupuesto (A4, mm). */
export const LAYOUT_PRESUPUESTO_IB: PlantillaLayout = {
  unidad: 'mm',
  anchoPagina: 210,
  altoPagina: 297,
  elementos: [
    {
      id: 'fiscal-row',
      type: 'fiscalRow',
      x: M,
      y: 10,
      width: W,
      height: 9,
      style: { fontSize: 7, borderColor: '#000', borderWidth: 1 },
      zIndex: 1,
    },
    {
      id: 'fecha',
      type: 'field',
      x: M,
      y: 21,
      width: 55,
      height: 5,
      binding: 'documento.fecha',
      label: 'Fecha: ',
      style: { fontSize: 8 },
      zIndex: 2,
    },
    {
      id: 'numero-doc',
      type: 'field',
      x: M + 95,
      y: 21,
      width: 87,
      height: 5,
      binding: 'documento.titulo',
      style: { fontSize: 11, fontWeight: 'bold', textAlign: 'right' },
      zIndex: 2,
    },
    {
      id: 'leyenda-no-fiscal',
      type: 'field',
      x: M,
      y: 27,
      width: W,
      height: 5,
      binding: 'documento.leyendaNoFiscal',
      style: { fontSize: 9, textAlign: 'center' },
      zIndex: 2,
    },
    {
      id: 'logo',
      type: 'image',
      x: M + 68,
      y: 33,
      width: 46,
      height: 16,
      binding: 'emisor.logo',
      content: '/logo.png',
      zIndex: 2,
    },
    {
      id: 'marca',
      type: 'field',
      x: M,
      y: 50,
      width: W,
      height: 6,
      binding: 'documento.marca',
      style: { fontSize: 14, fontWeight: 'bold', textAlign: 'center' },
      zIndex: 2,
    },
    {
      id: 'domicilio',
      type: 'field',
      x: M,
      y: 57,
      width: W,
      height: 5,
      binding: 'emisor.domicilio',
      style: { fontSize: 8, textAlign: 'center' },
      zIndex: 2,
    },
    {
      id: 'contacto',
      type: 'field',
      x: M,
      y: 62,
      width: W,
      height: 5,
      binding: 'emisor.contacto',
      style: { fontSize: 8, textAlign: 'center' },
      zIndex: 2,
    },
    {
      id: 'cliente-box',
      type: 'clienteBox',
      x: M,
      y: 70,
      width: W,
      height: 24,
      style: { fontSize: 8, borderColor: '#000', borderWidth: 1 },
      zIndex: 3,
    },
    {
      id: 'items-table',
      type: 'itemsTable',
      x: M,
      y: 98,
      width: W,
      height: 95,
      style: {
        fontSize: 8,
        backgroundColor: NARANJA,
        color: '#fff',
        borderColor: '#000',
        borderWidth: 1,
      },
      zIndex: 4,
    },
    {
      id: 'totals-box',
      type: 'totalsBox',
      x: M + 106,
      y: 198,
      width: 76,
      height: 32,
      style: { fontSize: 8, borderColor: '#000', borderWidth: 1 },
      zIndex: 5,
    },
    {
      id: 'en-letras',
      type: 'field',
      x: M,
      y: 234,
      width: W,
      height: 8,
      binding: 'totales.enLetras',
      style: { fontSize: 7, color: '#333' },
      zIndex: 5,
    },
    {
      id: 'observaciones',
      type: 'observacionesBlock',
      x: M,
      y: 246,
      width: W,
      height: 40,
      style: { fontSize: 8, borderColor: '#ccc', borderWidth: 1 },
      label: 'Observaciones:',
      zIndex: 6,
    },
  ],
}

export function crearIdElemento(): string {
  return `el-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`
}
